<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "hotel_numbers".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $description
 */
class HotelNumbers extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'hotel_numbers';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['name'], 'string', 'max' => 255],
            [['name'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'description' => 'Описание',
        ];
    }

    /**
     * Перед удалением номера необходимо отменить все бронирования связанные с ним
     *
     * @return bool
     */
    public function beforeDelete()
    {
        Bookings::deleteAll(['hotel_number_id' => $this->id]);

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * Получение массива номеров для выпадающего списка
     *
     * @return array
     */
    public static function getDropDownArray()
    {
        return ArrayHelper::map(self::find()->all(), 'id', 'name');
    }
}
